In [ ]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 59.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 64.1 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=44e16118565c1714fc799ec669f7f13b1c0d90d6a3bea2e1e2bfb0f42ccb91a5
  Stored in directory: /root/.cache/pip/wheels/71/67/06/162a3760c40d74dd40bc855d527008d26341c2b0ecf3e8e11f
Successfully built sentence-transformers


In [ ]:
Generate Embeding

In [ ]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
sentences = ['This framework generates embedding for each input sentence','Sentences are passed as a list of String']

embeddings = model.encode(sentences)

for sentence, embedding in zip(sentences,embeddings):
  print("Sentence:",sentence)
  print("Embeddings:",embedding)
  print("")

Sentence: This framework generates embedding for each input sentence
Embeddings: [-6.91256858e-03 -3.62894610e-02 -2.18610074e-02  1.13818049e-02
  4.25385050e-02  1.24863908e-01  3.01178619e-02 -3.15150246e-02
  3.38303857e-02 -7.66847357e-02  1.20255454e-02 -4.15239818e-02
  4.81980033e-02  1.67390052e-02 -7.33146071e-02  8.39759037e-02
  2.76713981e-03  4.19141427e-02 -4.62020636e-02 -1.12434991e-01
 -2.36533843e-02  6.44106269e-02  4.85518649e-02 -4.90318984e-02
 -4.05254923e-02  4.44705524e-02 -4.74039949e-02  6.91372575e-03
  1.09921902e-01  9.62933619e-03  3.35711241e-02 -3.39446329e-02
  1.79634579e-02  7.73302242e-02  3.85686615e-03  1.92318559e-02
 -1.43055450e-02  2.38439720e-02 -4.99975383e-02 -1.53257726e-02
 -2.34336369e-02 -1.26113985e-02  2.45836545e-02  1.66354403e-02
  8.51943269e-02 -4.40953597e-02 -8.38720277e-02 -1.40059963e-02
 -1.63426846e-02  1.66166890e-02 -8.57066214e-02 -5.24259321e-02
 -1.22594982e-02  2.15967540e-02 -2.22520493e-02  1.60497706e-02
 -1.09896

In [ ]:
Cosine-Similarity

In [ ]:
emb1 = model.encode("I am eating apple")
emb2 = model.encode("I like Fruits")
cos_sim = util.cos_sim(emb1,emb2)
print("Cosine Similarity:", cos_sim)

Cosine Similarity: tensor([[0.5398]])


In [ ]:
Compute cosine similarity between all pairs

In [ ]:
#Compute cosine similarity between all pairs
sentences =  ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

embeddings = model.encode(sentences)

cos_sim = util.cos_sim(embeddings,embeddings)

cos_sim

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0704, -0.0333,  0.1707,  0.0476,
          0.0630],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0809, -0.0216,  0.1157,  0.0362,
          0.0216],
        [-0.1050, -0.0610,  1.0000, -0.1088,  0.0217, -0.0413, -0.0928,  0.0231,
          0.0247],
        [ 0.2474,  0.1442, -0.1088,  1.0000, -0.0348,  0.0362,  0.7369,  0.0821,
          0.1389],
        [-0.0704, -0.0809,  0.0217, -0.0348,  1.0000, -0.1654, -0.0592,  0.1961,
          0.2564],
        [-0.0333, -0.0216, -0.0413,  0.0362, -0.1654,  1.0000,  0.0769, -0.0380,
         -0.0895],
        [ 0.1707,  0.1157, -0.0928,  0.7369, -0.0592,  0.0769,  1.0000,  0.0495,
          0.1191],
        [ 0.0476,  0.0362,  0.0231,  0.0821,  0.1961, -0.0380,  0.0495,  1.0000,
          0.6433],
        [ 0.0630,  0.0216,  0.0247,  0.1389,  0.2564, -0.0895,  0.1191,  0.6433,
          1.0000]])

In [ ]:
#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
  for j in range(i+1,len(cos_sim)):
    all_sentence_combinations.append((cos_sim[i][j],i,j))
all_sentence_combinations

[(tensor(0.7553), 0, 1),
 (tensor(-0.1050), 0, 2),
 (tensor(0.2474), 0, 3),
 (tensor(-0.0704), 0, 4),
 (tensor(-0.0333), 0, 5),
 (tensor(0.1707), 0, 6),
 (tensor(0.0476), 0, 7),
 (tensor(0.0630), 0, 8),
 (tensor(-0.0610), 1, 2),
 (tensor(0.1442), 1, 3),
 (tensor(-0.0809), 1, 4),
 (tensor(-0.0216), 1, 5),
 (tensor(0.1157), 1, 6),
 (tensor(0.0362), 1, 7),
 (tensor(0.0216), 1, 8),
 (tensor(-0.1088), 2, 3),
 (tensor(0.0217), 2, 4),
 (tensor(-0.0413), 2, 5),
 (tensor(-0.0928), 2, 6),
 (tensor(0.0231), 2, 7),
 (tensor(0.0247), 2, 8),
 (tensor(-0.0348), 3, 4),
 (tensor(0.0362), 3, 5),
 (tensor(0.7369), 3, 6),
 (tensor(0.0821), 3, 7),
 (tensor(0.1389), 3, 8),
 (tensor(-0.1654), 4, 5),
 (tensor(-0.0592), 4, 6),
 (tensor(0.1961), 4, 7),
 (tensor(0.2564), 4, 8),
 (tensor(0.0769), 5, 6),
 (tensor(-0.0380), 5, 7),
 (tensor(-0.0895), 5, 8),
 (tensor(0.0495), 6, 7),
 (tensor(0.1191), 6, 8),
 (tensor(0.6433), 7, 8)]

In [ ]:
#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x:x[0],reverse=True)
print("Top 5 most similar pairs")

for score, i,j in all_sentence_combinations[0:5]:
  print("{} \t {} \t {:.4f}".format(sentences[i],sentences[j],cos_sim[i][j]))

Top 5 most similar pairs
A man is eating food. 	 A man is eating a piece of bread. 	 0.7553
A man is riding a horse. 	 A man is riding a white horse on an enclosed ground. 	 0.7369
A monkey is playing drums. 	 Someone in a gorilla costume is playing a set of drums. 	 0.6433
A woman is playing violin. 	 Someone in a gorilla costume is playing a set of drums. 	 0.2564
A man is eating food. 	 A man is riding a horse. 	 0.2474


In [ ]:
Semantic search

In [ ]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('clips/mfaq')

/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py:379: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [ ]:
question = "How many models can I host on HuggingFace?"
answer_1 = "All plans come with unlimited private models and datasets."
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

query_embedding = model.encode(question)
corpus_embedding = model.encode([answer_1,answer_2,answer_3])

print(util.semantic_search(query_embedding,corpus_embedding))

[[{'corpus_id': 0, 'score': 0.5507140755653381}, {'corpus_id': 2, 'score': 0.4993181526660919}, {'corpus_id': 1, 'score': 0.4596717655658722}]]


In [ ]:
from transformers import pipeline

In [ ]:
qa_model = pipeline("question-answering")
question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."
qa_model(question=question,context=context)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.701717734336853, 'start': 20, 'end': 29, 'answer': 'unlimited'}

In [ ]:
print(util.semantic_search(query_embedding, corpus_embeddings))

RuntimeError: ignored

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

corpus=[
    'A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
]

corpus_embeddings = embedder.encode(corpus)

corpus_embeddings = corpus_embeddings/np.linalg.norm(corpus_embeddings,axis=1, keepdims=True)

In [ ]:
corpus_embeddings[0]
     

array([ 3.32415812e-02,  4.40610899e-03, -6.27700845e-03,  4.83787358e-02,
       -1.38702303e-01, -3.36174294e-02,  1.01128317e-01, -5.43849468e-02,
       -4.32477705e-02, -3.99410874e-02,  7.78634474e-03, -1.27489176e-02,
       -6.68302327e-02, -1.73865724e-02,  4.74505983e-02, -5.77242747e-02,
        1.01888388e-01, -9.11647337e-04,  8.22614953e-02, -5.03415577e-02,
        6.77303225e-02,  4.08765003e-02, -3.58018763e-02, -1.00682437e-01,
       -6.69353316e-03, -5.31686321e-02,  1.00335173e-01, -5.46136834e-02,
       -2.28481535e-02,  1.38387103e-02,  7.48658031e-02, -6.17880113e-02,
        6.39215931e-02,  1.62387453e-02, -5.32299578e-02, -3.86083946e-02,
        3.15275975e-02, -8.11530054e-02, -3.31432298e-02, -5.38525521e-04,
       -3.96068720e-03, -1.52733950e-02, -9.86412051e-04,  9.57987905e-02,
       -5.42920716e-02,  1.84571724e-02, -1.07143603e-01,  1.38885183e-02,
        3.94072160e-02, -2.69243363e-02, -9.15988907e-02, -1.14195561e-02,
        3.38136926e-02, -

In [ ]:
clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
clustering_assignment = clustering_model.labels_
print(clustering_assignment)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[0 0 3 0 0 1 1 3 3 2 2 3 3 3 1]


In [ ]:
from sklearn import cluster
clustered_sentences = {}
for sentence_id,cluster_id in enumerate(clustering_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 3: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 1: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 2: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}

In [ ]:
from sklearn import cluster
clustered_sentences = {}
for sentence_id,cluster_id in enumerate(clustering_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 3: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 1: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 2: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}